In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio
from sklearn.feature_extraction.text import TfidfTransformer

In [2]:
OHCO = ['country_id', 'article_id','section_id','subsection_id','sent_id','token_id']
bags = dict(
    SENTS = OHCO[:5],
    SUBS = OHCO[:4],
    SECT = OHCO[:3],
    ART = OHCO[:2],
    COUNTRY = OHCO[:1]
)

bag = 'ART'

In [3]:
data_prefix = 'const'
data_dir = "parsed_data"

In [4]:
LIB = pd.read_csv(f"{data_dir}/{data_prefix}_LIB.csv").set_index('doc_id')
TOKEN = pd.read_csv(f'{data_dir}/{data_prefix}_TOKEN.csv').set_index(OHCO).dropna()
VOCAB = pd.read_csv(f'{data_dir}/{data_prefix}_VOCAB.csv').set_index('term_str').dropna()

In [5]:
BOW = TOKEN.groupby(bags[bag]+['term_str']).term_str.count().to_frame('n') 
BOW.head()

                                        n
country_id       article_id term_str
Afghanistan_2004 0          2004        2
                            3           1
                            a           3
                            accordance  1
                            adhering    1

In [10]:
len(BOW)

844512

In [13]:
BOW.to_csv("const_BOW.csv")

In [6]:
DTM = BOW.unstack().fillna(0)
DTM.head(10)

                               n                                            \
term_str                       0   00  000  00w   01  010 01000 01285   02
country_id       article_id
Afghanistan_2004 0           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 1           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 2           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 3           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 4           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 5           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 6           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 7           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 8           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 9           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0

                                  ...                                         \
term_str                     020  ... ñappointing ñcreate ñsuspend ñthe  ñto
country_id       article_id       ...
Afghanistan_2004 0           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 1           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 2           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 3           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 4           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 5           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 6           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 7           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 8           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 9           0.0  ...         0.0     0.0      0.0  0.0  0.0


term_str                    órdenes órganos    ô örebro única
country_id       article_id
Afghanistan_2004 0              0.0     0.0  0.0    0.0   0.0
                 1              0.0     0.0  0.0    0.0   0.0
                 2              0.0     0.0  0.0    0.0   0.0
                 3              0.0     0.0  0.0    0.0   0.0
                 4              0.0     0.0  0.0    0.0   0.0
                 5              0.0     0.0  0.0    0.0   0.0
                 6              0.0     0.0  0.0    0.0   0.0
                 7              0.0     0.0  0.0    0.0   0.0
                 8              0.0     0.0  0.0    0.0   0.0
                 9              0.0     0.0  0.0    0.0   0.0

[10 rows x 24135 columns]

In [7]:
DTM.to_parquet("const_DTM.parquet")

In [14]:
tfidf = TfidfTransformer(norm=None)
TFIDF_matrix = tfidf.fit_transform(DTM)
TFIDF = pd.DataFrame(
    TFIDF_matrix.toarray(),
    index=DTM.index,
    columns=DTM.columns
)

In [15]:
TFIDF.to_parquet('const_TFIDF.parquet')

In [16]:
tfidf_l2 = TfidfTransformer(norm='l2')
TFIDF_matrix_l2 = tfidf_l2.fit_transform(DTM)
TFIDF_l2 = pd.DataFrame(
    TFIDF_matrix_l2.toarray(),
    index=DTM.index,
    columns=DTM.columns
)

In [17]:
TFIDF_l2.to_parquet("const_TFIDF_L2.parquet")

In [18]:
len(TFIDF_l2)

23433

In [19]:
TFIDF_l2.head()

                               n                                            \
term_str                       0   00  000  00w   01  010 01000 01285   02
country_id       article_id
Afghanistan_2004 0           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 1           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 2           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 3           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0
                 4           0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0

                                  ...                                         \
term_str                     020  ... ñappointing ñcreate ñsuspend ñthe  ñto
country_id       article_id       ...
Afghanistan_2004 0           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 1           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 2           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 3           0.0  ...         0.0     0.0      0.0  0.0  0.0
                 4           0.0  ...         0.0     0.0      0.0  0.0  0.0


term_str                    órdenes órganos    ô örebro única
country_id       article_id
Afghanistan_2004 0              0.0     0.0  0.0    0.0   0.0
                 1              0.0     0.0  0.0    0.0   0.0
                 2              0.0     0.0  0.0    0.0   0.0
                 3              0.0     0.0  0.0    0.0   0.0
                 4              0.0     0.0  0.0    0.0   0.0

[5 rows x 24135 columns]

In [22]:
num_features = TFIDF_l2.shape[1]
print(num_features)

24135