In [79]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [80]:
vdem = pd.read_csv("data/vdem/vdem.csv")

In [81]:
vdem.columns

Index(['country_name', 'country_text_id', 'country_id', 'year',
       'historical_date', 'project', 'historical', 'histname', 'codingstart',
       'codingend',
       ...
       'v2edplural_sd', 'v2edplural_osp', 'v2edplural_osp_codelow',
       'v2edplural_osp_codehigh', 'v2edplural_osp_sd', 'v2edplural_ord',
       'v2edplural_ord_codelow', 'v2edplural_ord_codehigh', 'v2edplural_mean',
       'v2edplural_nr'],
      dtype='object', length=1908)

In [82]:
dem_index = pd.read_csv("data/democracy-index-eiu/democracy-index-eiu.csv")

In [83]:
dem_index.head()

        Entity Code  Year  Democracy Index World region according to OWID
0  Afghanistan  AFG  2006             3.06                           Asia
1  Afghanistan  AFG  2008             3.02                           Asia
2  Afghanistan  AFG  2010             2.48                           Asia
3  Afghanistan  AFG  2011             2.48                           Asia
4  Afghanistan  AFG  2012             2.48                           Asia

In [84]:
vdem[(vdem['country_name'] == 'Afghanistan') & (vdem['year'] == 2006)]

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,v2edplural_sd,v2edplural_osp,v2edplural_osp_codelow,v2edplural_osp_codehigh,v2edplural_osp_sd,v2edplural_ord,v2edplural_ord_codelow,v2edplural_ord_codehigh,v2edplural_mean,v2edplural_nr
5566,Afghanistan,AFG,36,2006,2006-12-31,0,1,Islamic Republic of Afghanistan under US occup...,1789,2025,...,0.635,0.29,0.027,0.421,0.206,0.0,0.0,0.0,0.4,5.0

In [85]:
vdem['v2x_regime']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
28087   NaN
28088   NaN
28089   NaN
28090   NaN
28091   NaN
Name: v2x_regime, Length: 28092, dtype: float64

In [86]:
vdem_2024 = vdem[vdem['year']==2024]

In [87]:
vdem_2024.head()

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,v2edplural_sd,v2edplural_osp,v2edplural_osp_codelow,v2edplural_osp_codehigh,v2edplural_osp_sd,v2edplural_ord,v2edplural_ord_codelow,v2edplural_ord_codehigh,v2edplural_mean,v2edplural_nr
235,Mexico,MEX,3,2024,2024-12-31,0,1,United Mexican States,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,Suriname,SUR,4,2024,2024-12-31,0,0,Republic of Suriname [independent state],1900,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,Sweden,SWE,5,2024,2024-12-31,0,1,Kingdom of Sweden,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
826,Switzerland,CHE,6,2024,2024-12-31,0,1,Swiss Confederation,1798,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950,Ghana,GHA,7,2024,2024-12-31,0,0,Republic of Ghana,1902,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
vdem_2024["v2x_regime"].value_counts()

v2x_regime
1.0    59
2.0    56
0.0    34
3.0    30
Name: count, dtype: int64

In [89]:
regime_map = {
    0: "Closed autocracy",
    1: "Electoral autocracy",
    2: "Electoral democracy",
    3: "Liberal democracy"
}

vdem_2024['regime_type'] = vdem_2024['v2x_regime'].map(regime_map)

/var/folders/6g/_wpr8bs53rs84lqb6nn_rk900000gn/T/ipykernel_26746/4174736970.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vdem_2024['regime_type'] = vdem_2024['v2x_regime'].map(regime_map)

In [90]:
vdem_2024

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,v2edplural_osp,v2edplural_osp_codelow,v2edplural_osp_codehigh,v2edplural_osp_sd,v2edplural_ord,v2edplural_ord_codelow,v2edplural_ord_codehigh,v2edplural_mean,v2edplural_nr,regime_type
235,Mexico,MEX,3,2024,2024-12-31,0,1,United Mexican States,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral autocracy
361,Suriname,SUR,4,2024,2024-12-31,0,0,Republic of Suriname [independent state],1900,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral democracy
598,Sweden,SWE,5,2024,2024-12-31,0,1,Kingdom of Sweden,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Liberal democracy
826,Switzerland,CHE,6,2024,2024-12-31,0,1,Swiss Confederation,1798,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Liberal democracy
950,Ghana,GHA,7,2024,2024-12-31,0,0,Republic of Ghana,1902,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral democracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26072,Solomon Islands,SLB,203,2024,2024-12-31,0,0,Solomon Islands [independent state],1900,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral democracy
26198,Vanuatu,VUT,206,2024,2024-12-31,0,0,Republic of Vanuatu [independent state],1900,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral democracy
26253,United Arab Emirates,ARE,207,2024,2024-12-31,0,0,United Arab Emirates [Independent state formed...,1971,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Closed autocracy
26521,Hungary,HUN,210,2024,2024-12-31,0,1,Hungary,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral autocracy
26691,Zanzibar,ZZB,236,2024,2024-12-31,0,1,"Zanzibar, semi-autonomous region of Tanzania",1856,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electoral autocracy

In [91]:
dem_table = vdem_2024[['country_name', 'country_text_id', 'year', 'regime_type']]

In [92]:
dem_index.head()

        Entity Code  Year  Democracy Index World region according to OWID
0  Afghanistan  AFG  2006             3.06                           Asia
1  Afghanistan  AFG  2008             3.02                           Asia
2  Afghanistan  AFG  2010             2.48                           Asia
3  Afghanistan  AFG  2011             2.48                           Asia
4  Afghanistan  AFG  2012             2.48                           Asia

In [93]:
dem_index_2024 = dem_index[dem_index['Year']==2024]

In [94]:
dem_index_2024

,Entity,Code,Year,Democracy Index,World region according to OWID
16,Afghanistan,AFG,2024,0.250000,Asia
33,Africa,OWID_AFR,2024,3.916600,NaN
50,Africa (population-weighted),NaN,2024,3.828564,NaN
67,Albania,ALB,2024,6.200000,Europe
84,Algeria,DZA,2024,3.550000,Africa
...,...,...,...,...,...
3008,World,OWID_WRL,2024,5.174551,NaN
3025,World (population-weighted),NaN,2024,4.922441,NaN
3042,Yemen,YEM,2024,1.950000,Asia
3059,Zambia,ZMB,2024,5.730000,Africa
3076,Zimbabwe,ZWE,2024,2.980000,Africa

In [95]:
merged = pd.merge(
    dem_table,
    dem_index_2024,
    left_on='country_name',
    right_on='Entity',
    how='left'
)

In [96]:
merged.head()

,country_name,country_text_id,year,regime_type,Entity,Code,Year,Democracy Index,World region according to OWID
0,Mexico,MEX,2024,Electoral autocracy,Mexico,MEX,2024.0,5.32,North America
1,Suriname,SUR,2024,Electoral democracy,Suriname,SUR,2024.0,6.79,South America
2,Sweden,SWE,2024,Liberal democracy,Sweden,SWE,2024.0,9.39,Europe
3,Switzerland,CHE,2024,Liberal democracy,Switzerland,CHE,2024.0,9.32,Europe
4,Ghana,GHA,2024,Electoral democracy,Ghana,GHA,2024.0,6.24,Africa

In [100]:
merged = merged.drop(['Code', 'Year', 'Entity'], axis=1)

In [101]:
merged.head()

,country_name,country_text_id,year,regime_type,Democracy Index,World region according to OWID
0,Mexico,MEX,2024,Electoral autocracy,5.32,North America
1,Suriname,SUR,2024,Electoral democracy,6.79,South America
2,Sweden,SWE,2024,Liberal democracy,9.39,Europe
3,Switzerland,CHE,2024,Liberal democracy,9.32,Europe
4,Ghana,GHA,2024,Electoral democracy,6.24,Africa

In [108]:
merged

,country_name,country_text_id,year,regime_type,Democracy Index,World region according to OWID
0,Mexico,MEX,2024,Electoral autocracy,5.32,North America
1,Suriname,SUR,2024,Electoral democracy,6.79,South America
2,Sweden,SWE,2024,Liberal democracy,9.39,Europe
3,Switzerland,CHE,2024,Liberal democracy,9.32,Europe
4,Ghana,GHA,2024,Electoral democracy,6.24,Africa
...,...,...,...,...,...,...
174,Solomon Islands,SLB,2024,Electoral democracy,NaN,NaN
175,Vanuatu,VUT,2024,Electoral democracy,NaN,NaN
176,United Arab Emirates,ARE,2024,Closed autocracy,3.07,Asia
177,Hungary,HUN,2024,Electoral autocracy,6.51,Europe
178,Zanzibar,ZZB,2024,Electoral autocracy,NaN,NaN

In [110]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    179 non-null    object
 1   country_text_id                 179 non-null    object
 2   year                            179 non-null    int64
 3   regime_type                     179 non-null    object
 4   Democracy Index                 158 non-null    float64
 5   World region according to OWID  158 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 8.5+ KB

In [112]:
merged[merged['Democracy Index'].isnull()]

,country_name,country_text_id,year,regime_type,Democracy Index,World region according to OWID
7,Burma/Myanmar,MMR,2024,Closed autocracy,NaN,NaN
15,United States of America,USA,2024,Liberal democracy,NaN,NaN
26,South Sudan,SSD,2024,Closed autocracy,NaN,NaN
36,Kosovo,XKX,2024,Electoral democracy,NaN,NaN
57,Ivory Coast,CIV,2024,Electoral autocracy,NaN,NaN
67,Timor-Leste,TLS,2024,Electoral democracy,NaN,NaN
81,Maldives,MDV,2024,Electoral democracy,NaN,NaN
92,Türkiye,TUR,2024,Electoral autocracy,NaN,NaN
104,Democratic Republic of the Congo,COD,2024,Electoral autocracy,NaN,NaN
105,Republic of the Congo,COG,2024,Electoral autocracy,NaN,NaN
110,The Gambia,GMB,2024,Electoral democracy,NaN,NaN
121,Palestine/West Bank,PSE,2024,Electoral autocracy,NaN,NaN
123,Somalia,SOM,2024,Closed autocracy,NaN,NaN
130,Palestine/Gaza,PSG,2024,Closed autocracy,NaN,NaN
131,Somaliland,SML,2024,Electoral autocracy,NaN,NaN
135,Barbados,BRB,2024,Liberal democracy,NaN,NaN
167,Sao Tome and Principe,STP,2024,Electoral democracy,NaN,NaN
170,Seychelles,SYC,2024,Liberal democracy,NaN,NaN
174,Solomon Islands,SLB,2024,Electoral democracy,NaN,NaN
175,Vanuatu,VUT,2024,Electoral democracy,NaN,NaN
178,Zanzibar,ZZB,2024,Electoral autocracy,NaN,NaN

In [120]:
data = pd.read_csv("merged_democracy_data.csv")

In [121]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,169,170,171,172,173,174,175,176,177,178
country_name,Mexico,Suriname,Sweden,Switzerland,Ghana,South Africa,Japan,Burma/Myanmar,Russia,Albania,...,Serbia,Seychelles,Singapore,Slovakia,Slovenia,Solomon Islands,Vanuatu,United Arab Emirates,Hungary,Zanzibar
country_text_id,MEX,SUR,SWE,CHE,GHA,ZAF,JPN,MMR,RUS,ALB,...,SRB,SYC,SGP,SVK,SVN,SLB,VUT,ARE,HUN,ZZB
year,2024,2024,2024,2024,2024,2024,2024,2024,2024,2024,...,2024,2024,2024,2024,2024,2024,2024,2024,2024,2024
electoral_democracy,0.496,0.767,0.881,0.882,0.665,0.734,0.822,0.08,0.171,0.51,...,0.315,0.737,0.418,0.746,0.725,0.688,0.8,0.104,0.444,0.288
liberal_democracy,0.246,0.634,0.846,0.843,0.56,0.648,0.737,0.015,0.057,0.398,...,0.225,0.652,0.348,0.59,0.63,0.536,0.686,0.077,0.325,0.247
participatory_democracy,0.342,0.5,0.629,0.785,0.318,0.463,0.526,0.046,0.121,0.305,...,0.223,0.322,0.116,0.521,0.549,0.424,0.514,0.031,0.278,0.158
deliberative_democracy,0.266,0.605,0.809,0.852,0.544,0.647,0.732,0.036,0.05,0.256,...,0.21,0.679,0.344,0.37,0.618,0.39,0.61,0.082,0.186,0.275
egalitarian_democracy,0.276,0.576,0.794,0.82,0.459,0.512,0.752,0.057,0.129,0.367,...,0.283,0.612,0.36,0.582,0.635,0.433,0.623,0.126,0.313,0.248
freedom_expression,0.645,0.888,0.946,0.967,0.857,0.835,0.849,0.037,0.08,0.693,...,0.438,0.822,0.348,0.807,0.752,0.84,0.884,0.062,0.512,0.502
freedom_association,0.709,0.879,0.921,0.917,0.881,0.894,0.925,0.095,0.125,0.812,...,0.655,0.832,0.584,0.838,0.861,0.874,0.888,0.04,0.655,0.657
suffrage,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.36,1.0,1.0
free_fair_elections,0.592,0.843,0.945,0.942,0.657,0.812,0.942,0.0,0.142,0.487,...,0.207,0.888,0.806,0.93,0.916,0.73,0.897,0.543,0.605,0.118
rule_of_law,0.533,0.903,0.983,0.982,0.858,0.865,0.958,0.09,0.303,0.905,...,0.863,0.964,0.903,0.877,0.944,0.832,0.891,0.495,0.872,0.671
judicial_constraints,0.394,0.839,0.976,0.982,0.827,0.918,0.881,0.025,0.046,0.648,...,0.433,0.952,0.846,0.838,0.779,0.826,0.911,0.141,0.63,0.613
legislative_constraints,0.243,0.745,0.989,0.956,0.877,0.926,0.901,NaN,0.073,0.692,...,0.354,0.8,0.561,0.607,0.917,0.648,0.792,0.138,0.497,0.715
regime_type,1.0,2.0,3.0,3.0,2.0,2.0,3.0,0.0,1.0,2.0,...,1.0,3.0,1.0,2.0,2.0,2.0,2.0,0.0,1.0,1.0
accountability,0.497,1.274,1.815,1.826,1.204,1.375,1.494,-1.342,-0.973,0.748,...,0.161,1.303,0.355,1.133,1.256,1.061,1.403,-0.661,0.446,0.2
presidentialism,0.548,0.156,0.017,0.019,0.145,0.066,0.094,0.981,0.942,0.293,...,0.538,0.051,0.225,0.141,0.166,0.192,0.093,0.843,0.367,0.361
civil_liberties,0.63,0.91,0.961,0.951,0.889,0.867,0.925,0.102,0.26,0.876,...,0.775,0.904,0.714,0.861,0.889,0.857,0.892,0.346,0.824,0.65
political_exclusion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
political_corruption,0.581,0.14,0.009,0.023,0.638,0.517,0.05,0.859,0.795,0.627,...,0.76,0.047,0.032,0.278,0.057,0.602,0.279,0.105,0.494,0.525
public_sector_corruption,0.487,0.221,0.019,0.007,0.665,0.751,0.036,0.839,0.781,0.651,...,0.641,0.093,0.009,0.18,0.064,0.608,0.195,0.116,0.202,0.607
gender_equality_index,0.798,0.898,0.924,0.939,0.798,0.839,0.795,0.333,0.535,0.901,...,0.887,0.887,0.78,0.879,0.939,0.675,0.694,0.6,0.832,0.692
fh_political_rights,27.0,34.0,40.0,39.0,35.0,33.0,40.0,NaN,4.0,28.0,...,18.0,34.0,19.0,37.0,39.0,28.0,32.0,5.0,24.0,NaN
fh_civil_liberties,33.0,45.0,59.0,57.0,45.0,46.0,56.0,NaN,9.0,40.0,...,39.0,45.0,29.0,53.0,57.0,47.0,50.0,13.0,41.0,NaN
fh_total_score,60.0,79.0,99.0,96.0,80.0,79.0,96.0,NaN,13.0,68.0,...,57.0,79.0,48.0,90.0,96.0,75.0,82.0,18.0,65.0,NaN
fh_status,PF,F,F,F,F,F,F,NaN,NF,PF,...,PF,F,PF,F,F,F,F,NF,PF,NaN

In [122]:
data[data['country_name']=='Mexico']

,country_name,country_text_id,year,electoral_democracy,liberal_democracy,participatory_democracy,deliberative_democracy,egalitarian_democracy,freedom_expression,freedom_association,...,presidentialism,civil_liberties,political_exclusion,political_corruption,public_sector_corruption,gender_equality_index,fh_political_rights,fh_civil_liberties,fh_total_score,fh_status
0,Mexico,MEX,2024,0.496,0.246,0.342,0.266,0.276,0.645,0.709,...,0.548,0.63,NaN,0.581,0.487,0.798,27.0,33.0,60.0,PF