In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

In [72]:
OHCO = ['country_id', 'article_id','section_id','subsection_id','sent_id','token_id']

In [73]:
data_prefix = 'const'
data_dir = "parsed_data"

In [74]:
LIB = pd.read_csv(f'{data_dir}/{data_prefix}_LIB.csv',  index_col=0)
CORPUS = pd.read_csv(f'{data_dir}/{data_prefix}_TOKEN.csv').set_index(OHCO)

In [75]:
REGIME_LABELS = {
    0: "Closed Autocracy",
    1: "Electoral Autocracy",
    2: "Electoral Democracy",
    3: "Liberal Democracy",
}

LIB['regime_label'] = LIB['regime_type'].map(REGIME_LABELS)
LIB.head(3).T

doc_id,Afghanistan_2004,Albania_2008,Algeria_2008
country_name,Afghanistan,Albania,Algeria
year_amended,2004,2008,2008
doc_len,66806,86022,66590
country_text_id,AFG,ALB,DZA
dem_year,2024.0,2024.0,2024.0
electoral_democracy,0.08,0.51,0.26
liberal_democracy,0.014,0.398,0.123
participatory_democracy,0.012,0.305,0.094
deliberative_democracy,0.024,0.256,0.169
egalitarian_democracy,0.028,0.367,0.24
freedom_expression,0.08,0.693,0.348
freedom_association,0.05,0.812,0.302
suffrage,1.0,1.0,1.0
free_fair_elections,0.0,0.487,0.308
rule_of_law,0.016,0.905,0.48
judicial_constraints,0.095,0.648,0.133
legislative_constraints,0.174,0.692,0.273
regime_type,0.0,2.0,1.0
accountability,-1.333,0.748,-0.255
presidentialism,0.944,0.293,0.818
civil_liberties,0.042,0.876,0.418
political_exclusion,NaN,NaN,NaN
political_corruption,0.681,0.627,0.662
public_sector_corruption,0.686,0.651,0.595
gender_equality_index,0.049,0.901,0.625
fh_political_rights,1.0,28.0,10.0
fh_civil_liberties,5.0,40.0,22.0
fh_total_score,6.0,68.0,32.0
fh_status,NF,PF,NF
regime_label,Closed Autocracy,Electoral Democracy,Electoral Autocracy

In [76]:
print(LIB.columns)

Index(['country_name', 'year_amended', 'doc_len', 'country_text_id',
       'dem_year', 'electoral_democracy', 'liberal_democracy',
       'participatory_democracy', 'deliberative_democracy',
       'egalitarian_democracy', 'freedom_expression', 'freedom_association',
       'suffrage', 'free_fair_elections', 'rule_of_law',
       'judicial_constraints', 'legislative_constraints', 'regime_type',
       'accountability', 'presidentialism', 'civil_liberties',
       'political_exclusion', 'political_corruption',
       'public_sector_corruption', 'gender_equality_index',
       'fh_political_rights', 'fh_civil_liberties', 'fh_total_score',
       'fh_status', 'regime_label'],
      dtype='object')

In [77]:
LIB.head()

,country_name,year_amended,doc_len,country_text_id,dem_year,electoral_democracy,liberal_democracy,participatory_democracy,deliberative_democracy,egalitarian_democracy,...,civil_liberties,political_exclusion,political_corruption,public_sector_corruption,gender_equality_index,fh_political_rights,fh_civil_liberties,fh_total_score,fh_status,regime_label
doc_id,,,,,,,,,,,,,,,,,,,,,
Afghanistan_2004,Afghanistan,2004,66806,AFG,2024.0,0.080,0.014,0.012,0.024,0.028,...,0.042,NaN,0.681,0.686,0.049,1.0,5.0,6.0,NF,Closed Autocracy
Albania_2008,Albania,2008,86022,ALB,2024.0,0.510,0.398,0.305,0.256,0.367,...,0.876,NaN,0.627,0.651,0.901,28.0,40.0,68.0,PF,Electoral Democracy
Algeria_2008,Algeria,2008,66590,DZA,2024.0,0.260,0.123,0.094,0.169,0.240,...,0.418,NaN,0.662,0.595,0.625,10.0,22.0,32.0,NF,Electoral Autocracy
Andorra_1993,Andorra,1993,55687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola_2010,Angola,2010,175148,AGO,2024.0,0.342,0.161,0.100,0.161,0.128,...,0.624,NaN,0.546,0.471,0.757,10.0,18.0,28.0,NF,Electoral Autocracy

In [78]:
table_dir = 'derived_tables'

In [79]:
DTM = pd.read_parquet(f'{table_dir}/const_DTM.parquet')

In [80]:
DTM.head()

term_str,0,00,000,00000,005,00w,01,010,01000,0101,...,ñcreate,ñsuspend,ñthe,ñto,órdenes,órgano,órganos,ô,örebro,única
country_id,,,,,,,,,,,,,,,,,,,,,
Afghanistan_2004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Albania_2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Algeria_2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Andorra_1993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Angola_2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [81]:
VOCAB = DTM.sum().to_frame('n')
VOCAB['p'] = VOCAB.n / VOCAB.n.sum()
VOCAB['i'] = np.log2(1/VOCAB.p)
VOCAB['df'] = DTM.astype(bool).sum()
VOCAB['dfidf'] = VOCAB.df * np.log2(len(DTM)/VOCAB.df)

In [82]:
TFIDF = pd.read_parquet(f'{table_dir}/const_TFIDF_L2.parquet')

In [83]:
TFIDF.head()

term_str,0,00,000,00000,005,00w,01,010,01000,0101,...,ñcreate,ñsuspend,ñthe,ñto,órdenes,órgano,órganos,ô,örebro,única
country_id,,,,,,,,,,,,,,,,,,,,,
Afghanistan_2004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Albania_2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Algeria_2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Andorra_1993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Angola_2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [84]:
VOCAB.head()

             n             p          i  df      dfidf
term_str
0         15.0  3.518343e-06  18.116672   4  22.339850
00         6.0  1.407337e-06  19.438600   1   7.584963
000        9.0  2.111006e-06  18.853638   2  13.169925
00000      1.0  2.345562e-07  22.023563   1   7.584963
005        1.0  2.345562e-07  22.023563   1   7.584963

In [85]:
VOCAB.index

Index(['0', '00', '000', '00000', '005', '00w', '01', '010', '01000', '0101',
       ...
       'ñcreate', 'ñsuspend', 'ñthe', 'ñto', 'órdenes', 'órgano', 'órganos',
       'ô', 'örebro', 'única'],
      dtype='object', name='term_str', length=39729)

In [86]:
fig = px.scatter(
    VOCAB,
    x='i',
    y='df',
    hover_name=VOCAB.index,  # or 'level_0'
    width=800
)

fig.show()

In [87]:
df_thresh = 50 # Remove proper nouns and one-offs
i_thresh = 10 # Remove stopwords
SIGS = VOCAB[(VOCAB.df >= df_thresh) & (VOCAB.i > i_thresh)].index
len(SIGS)

2388

In [88]:
TFIDF_SIGS = TFIDF[SIGS].copy()

In [89]:
from sklearn.decomposition import PCA

n_components = 5
pca_engine = PCA(n_components=n_components, random_state=42)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF_SIGS), index=TFIDF_SIGS.index)
DCM

                         0         1         2         3         4
country_id
Afghanistan_2004 -0.028382 -0.002887 -0.018438 -0.001459  0.003236
Albania_2008     -0.026667 -0.007603 -0.013054 -0.009036 -0.012077
Algeria_2008     -0.027866 -0.005583  0.000174  0.004471 -0.017094
Andorra_1993     -0.018301 -0.006129 -0.002530 -0.006481 -0.005002
Angola_2010      -0.026833 -0.001321 -0.028927 -0.014584  0.007475
...                    ...       ...       ...       ...       ...
Vanuatu_1983      0.029709 -0.001427 -0.005559 -0.009124  0.001722
Venezuela_2009   -0.030429 -0.002501 -0.021046 -0.004795  0.017241
Yemen_2001       -0.024788 -0.000252 -0.006106 -0.001072  0.010565
Zambia_2009       0.075889 -0.001894 -0.001514 -0.024131 -0.002682
Zimbabwe_2013     0.032442 -0.011839 -0.000541  0.007195  0.027374

[192 rows x 5 columns]

In [90]:
pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_)

array([[ 4.28037397e-04,  1.74001218e-05, -7.15426353e-06,
         2.92574663e-05,  4.28077583e-04],
       [-8.07301179e-05, -4.26871794e-05,  3.01904911e-05,
        -6.74596801e-06, -6.60928609e-05],
       [-8.92508831e-05, -4.40771588e-05,  3.15463888e-05,
        -1.08748957e-05, -4.74636786e-05],
       ...,
       [ 4.06346131e-04,  1.36542451e-04,  6.80655175e-04,
        -7.88869076e-05,  7.70655947e-04],
       [-1.77333034e-04, -7.95878228e-05, -1.07064298e-04,
        -1.50638310e-04,  2.52043778e-05],
       [-3.30786074e-04, -4.07154899e-05, -8.99955281e-05,
        -4.66035774e-05, -5.35719541e-05]])

In [91]:
LOADINGS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_), index=TFIDF_SIGS.columns)
LOADINGS.index.name = 'term_str'
LOADINGS

                 0         1         2         3         4
term_str
10        0.000428  0.000017 -0.000007  0.000029  0.000428
100      -0.000081 -0.000043  0.000030 -0.000007 -0.000066
101      -0.000089 -0.000044  0.000032 -0.000011 -0.000047
102      -0.000079 -0.000037  0.000022 -0.000027 -0.000045
103      -0.000088 -0.000030 -0.000001  0.000019 -0.000061
...            ...       ...       ...       ...       ...
xiii     -0.000042 -0.000005  0.000009  0.000189  0.000091
xiv      -0.000039 -0.000009  0.000033  0.000126  0.000093
year      0.000406  0.000137  0.000681 -0.000079  0.000771
young    -0.000177 -0.000080 -0.000107 -0.000151  0.000025
youth    -0.000331 -0.000041 -0.000090 -0.000047 -0.000054

[2388 rows x 5 columns]

In [92]:
DOC = (
    pd.DataFrame(index=DTM.index)
    .reset_index()
    .join(LIB, on='country_id')
    .set_index(['country_id'])
)
DOC

,country_name,year_amended,doc_len,country_text_id,dem_year,electoral_democracy,liberal_democracy,participatory_democracy,deliberative_democracy,egalitarian_democracy,...,civil_liberties,political_exclusion,political_corruption,public_sector_corruption,gender_equality_index,fh_political_rights,fh_civil_liberties,fh_total_score,fh_status,regime_label
country_id,,,,,,,,,,,,,,,,,,,,,
Afghanistan_2004,Afghanistan,2004,66806,AFG,2024.0,0.080,0.014,0.012,0.024,0.028,...,0.042,NaN,0.681,0.686,0.049,1.0,5.0,6.0,NF,Closed Autocracy
Albania_2008,Albania,2008,86022,ALB,2024.0,0.510,0.398,0.305,0.256,0.367,...,0.876,NaN,0.627,0.651,0.901,28.0,40.0,68.0,PF,Electoral Democracy
Algeria_2008,Algeria,2008,66590,DZA,2024.0,0.260,0.123,0.094,0.169,0.240,...,0.418,NaN,0.662,0.595,0.625,10.0,22.0,32.0,NF,Electoral Autocracy
Andorra_1993,Andorra,1993,55687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola_2010,Angola,2010,175148,AGO,2024.0,0.342,0.161,0.100,0.161,0.128,...,0.624,NaN,0.546,0.471,0.757,10.0,18.0,28.0,NF,Electoral Autocracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vanuatu_1983,Vanuatu,1983,52183,VUT,2024.0,0.800,0.686,0.514,0.610,0.623,...,0.892,NaN,0.279,0.195,0.694,32.0,50.0,82.0,F,Electoral Democracy
Venezuela_2009,Venezuela,2009,240449,VEN,2024.0,0.196,0.046,0.154,0.025,0.094,...,0.335,NaN,0.970,0.985,0.759,1.0,14.0,15.0,NF,Electoral Autocracy
Yemen_2001,Yemen,2001,68130,YEM,2024.0,0.126,0.047,0.071,0.045,0.033,...,0.217,NaN,0.910,0.828,0.171,1.0,9.0,10.0,NF,Closed Autocracy
Zambia_2009,Zambia,2009,181924,ZMB,2024.0,0.512,0.390,0.355,0.429,0.330,...,0.826,NaN,0.351,0.556,0.810,23.0,31.0,54.0,PF,Electoral Democracy
Zimbabwe_2013,Zimbabwe,2013,348577,ZWE,2024.0,0.272,0.156,0.204,0.208,0.142,...,0.380,NaN,0.824,0.857,0.715,10.0,17.0,27.0,NF,Electoral Autocracy

In [93]:
LOADINGS.head()

                 0         1         2         3         4
term_str
10        0.000428  0.000017 -0.000007  0.000029  0.000428
100      -0.000081 -0.000043  0.000030 -0.000007 -0.000066
101      -0.000089 -0.000044  0.000032 -0.000011 -0.000047
102      -0.000079 -0.000037  0.000022 -0.000027 -0.000045
103      -0.000088 -0.000030 -0.000001  0.000019 -0.000061

In [94]:
def vis_pcs(x, y, color_col):
    return px.scatter(DCM.join(DOC), x, y, 
                      color=color_col, 
                      hover_name='country_name',
                      marginal_x='box', 
                      height=1000)

In [95]:
def vis_loadings(x, y):
    return px.scatter(LOADINGS.join(VOCAB), x, y, 
                      hover_name=LOADINGS.index, 
                      height=1000, 
                      size='df',
                      color='i',
                      text=LOADINGS.index)

In [96]:
LIB.head(3).T

doc_id,Afghanistan_2004,Albania_2008,Algeria_2008
country_name,Afghanistan,Albania,Algeria
year_amended,2004,2008,2008
doc_len,66806,86022,66590
country_text_id,AFG,ALB,DZA
dem_year,2024.0,2024.0,2024.0
electoral_democracy,0.08,0.51,0.26
liberal_democracy,0.014,0.398,0.123
participatory_democracy,0.012,0.305,0.094
deliberative_democracy,0.024,0.256,0.169
egalitarian_democracy,0.028,0.367,0.24
freedom_expression,0.08,0.693,0.348
freedom_association,0.05,0.812,0.302
suffrage,1.0,1.0,1.0
free_fair_elections,0.0,0.487,0.308
rule_of_law,0.016,0.905,0.48
judicial_constraints,0.095,0.648,0.133
legislative_constraints,0.174,0.692,0.273
regime_type,0.0,2.0,1.0
accountability,-1.333,0.748,-0.255
presidentialism,0.944,0.293,0.818
civil_liberties,0.042,0.876,0.418
political_exclusion,NaN,NaN,NaN
political_corruption,0.681,0.627,0.662
public_sector_corruption,0.686,0.651,0.595
gender_equality_index,0.049,0.901,0.625
fh_political_rights,1.0,28.0,10.0
fh_civil_liberties,5.0,40.0,22.0
fh_total_score,6.0,68.0,32.0
fh_status,NF,PF,NF
regime_label,Closed Autocracy,Electoral Democracy,Electoral Autocracy

In [97]:
fig = vis_pcs(0, 1, 'regime_label')
fig.show()
fig.write_image('figures/pca_1_regime_label.png')

In [98]:
fig_l = vis_loadings(0, 1)
fig_l.show()
fig_l.write_image('figures/pca_1_loadings.png')

In [99]:
fig = vis_pcs(3, 4, 'suffrage')
fig.show()
fig.write_image('figures/pca_2_suffrage.png')

In [100]:
fig_l = vis_loadings(3, 4)
fig_l.show()
fig_l.write_image('figures/pca_2_loadings.png')

In [101]:
pc_cols = [f'PC{i+1}' for i in range(n_components)]

DCM.columns = pc_cols
LOADINGS.columns = pc_cols

In [102]:
DCM.head()

                       PC1       PC2       PC3       PC4       PC5
country_id
Afghanistan_2004 -0.028382 -0.002887 -0.018438 -0.001459  0.003236
Albania_2008     -0.026667 -0.007603 -0.013054 -0.009036 -0.012077
Algeria_2008     -0.027866 -0.005583  0.000174  0.004471 -0.017094
Andorra_1993     -0.018301 -0.006129 -0.002530 -0.006481 -0.005002
Angola_2010      -0.026833 -0.001321 -0.028927 -0.014584  0.007475

In [103]:
LOADINGS.head()

               PC1       PC2       PC3       PC4       PC5
term_str
10        0.000428  0.000017 -0.000007  0.000029  0.000428
100      -0.000081 -0.000043  0.000030 -0.000007 -0.000066
101      -0.000089 -0.000044  0.000032 -0.000011 -0.000047
102      -0.000079 -0.000037  0.000022 -0.000027 -0.000045
103      -0.000088 -0.000030 -0.000001  0.000019 -0.000061

In [104]:
DCM.to_parquet(f'{table_dir}/const_DCM.parquet')
LOADINGS.to_parquet(f'{table_dir}/const_LOADINGS.parquet')

EXPLAINED = pd.DataFrame({
    'component': pc_cols,
    'explained_variance_ratio': pca_engine.explained_variance_ratio_,
    'explained_variance': pca_engine.explained_variance_
})

EXPLAINED.to_csv(f'{table_dir}/const_PCA_EXPLAINED.csv', index=False)

In [105]:
import pickle

with open(f'{table_dir}/const_pca_engine.pkl', 'wb') as f:
    pickle.dump(pca_engine, f)

In [106]:
top_pos_pc1 = LOADINGS['PC1'].sort_values(ascending=False).head(5)
print("Top 5 positive terms for PC1:")
print(top_pos_pc1)

# Top 5 negative terms for PC2
top_neg_pc2 = LOADINGS['PC2'].sort_values(ascending=True).head(5)
print("\nTop 5 negative terms for PC2:")
print(top_neg_pc2)

Top 5 positive terms for PC1:
term_str
speaker    0.009184
clause     0.006516
acting     0.005660
advice     0.005481
officer    0.004928
Name: PC1, dtype: float64

Top 5 negative terms for PC2:
term_str
chamber    -0.004758
deputies   -0.002350
must       -0.001497
senate     -0.001386
organic    -0.001243
Name: PC2, dtype: float64